services:
  node-app:
    container_name: node-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo-init
    volumes:
      - .:/app

      - /app/node_modules

    command: npm run start:dev

  mongo:
    container_name: mongo
    image: mongo:latest
    command: --replSet rs0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: attachment-api-local-dev
    healthcheck:
      # use 'mongo' instead of 'mongosh' if MongoDB version is lower than 5
      test: mongosh --eval 'db.runCommand("ping").ok' localhost:27017/test --quiet
      interval: 2s
      timeout: 3s
      retries: 5

  mongo-init:
    container_name: mongo_init
    image: mongo:latest
    restart: "no"
    depends_on:
      mongo:
        condition: service_healthy
    command: >
      mongosh --host mongo:27017 --eval
      '
      rs.initiate( {
         _id : "rs0",
         members: [
            { _id: 1, host: "mongo:27017" },
         ]
      })
      '
